
options:
  max-time: 5

pipelines:
  tags:
    v*:
      - step:
          name: Deploy to Docker Hub
          image: python:3.7
          trigger: manual
          services: [docker]
          deployment: container
          script:
            - export TAG=${BITBUCKET_TAG#v}
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build --build-arg version=$TAG -f docker/Dockerfile -t cccs/assemblyline-service-characterize:$TAG -t cccs/assemblyline-service-characterize:latest .
            - docker push cccs/assemblyline-service-characterize
